from lib import Manager

manager = Manager()
print(manager.cwd)
manager.mkdir("subaru")
manager.create("natsuki")
manager.create("yuri")
# manager.open("./subaru/../subaru/../natsuki", "w")
# manager.open("./subaru/../subaru/../yuri", "w")
# manager.ls()
print(manager.cwd)
# manager.close("./subaru/../subaru/../natsuki")
manager.chDir("subaru")
manager.mkdir("sule")
manager.chDir("~")
manager.chDir("~/subaru/sule")
# manager.create("sayori")
print(manager.cwd)
